Repository qp-official-org/QP_BACKEND, pull requests merged in 2024-02, with the labels that each got.

#83 [feat] OAuth 통한 회원 가입 및 로그인 구현 (카카오)
  build.gradle
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/apiPayload/exception/handler/UserHandler.java
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/repository/UserRepository.java
  src/main/java/qp/official/qp/service/UserService.java
  src/main/java/qp/official/qp/service/UserServiceImpl.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
  src/main/java/qp/official/qp/web/dto/UserAuthDTO.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
  src/main/resources/application.yml
Labels: feat, refactor

#91 [refactor] 자동 로그인 구현 및 TokenService 캡슐화
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/service/TokenService/TokenService.java
  src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
  src/main/java/qp/official/qp/service/UserService.java
  src/main/java/qp/official/qp/service/UserServiceImpl.java
  src/main/java/qp/official/qp/web/controller/AnswerRestController.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/controller/TokenController.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
  src/main/java/qp/official/qp/web/dto/TokenRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
Labels: feat, refactor

#96 [fix] CORS 해결
  src/main/java/qp/official/qp/web/controller/AnswerReportController.java
  src/main/java/qp/official/qp/web/controller/AnswerRestController.java
  src/main/java/qp/official/qp/web/controller/HashtagController.java
  src/main/java/qp/official/qp/web/controller/ImageController.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/controller/QuestionReportController.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
Labels: bug

#97 [fix] CORS 해결
  src/main/java/qp/official/qp/web/controller/AnswerReportController.java
  src/main/java/qp/official/qp/web/controller/AnswerRestController.java
  src/main/java/qp/official/qp/web/controller/HashtagController.java
  src/main/java/qp/official/qp/web/controller/ImageController.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/controller/QuestionReportController.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
Labels: bug

#98 [refactor] 코드 리팩토링 및 정리 작업
  src/main/java/qp/official/qp/apiPayload/ApiResponse.java
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/apiPayload/exception/handler/ImageHandler.java
  src/main/java/qp/official/qp/config/S3Config.java
  src/main/java/qp/official/qp/config/SecretConfig.java
  src/main/java/qp/official/qp/converter/AnswerConverter.java
  src/main/java/qp/official/qp/converter/ImageConverter.java
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/domain/Image.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/repository/AnswerLikesRepository.java
  src/main/java/qp/official/qp/repository/AnswerReportRepository.java
  src/main/java/qp/official/qp/repository/AnswerRepository.java
  src/main/java/qp/official/qp/repository/ImageRepository.java
  src/main/java/qp/official/qp/repository/UserRepository.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandService.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerQueryServiceImpl.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagService.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagServiceImpl.java
  src/main/java/qp/official/qp/service/ImageService/ImageCommandService.java
  src/main/java/qp/official/qp/service/ImageService/ImageCommandServiceImpl.java
  src/main/java/qp/official/qp/service/ImageService/ImageQueryServiceImpl.java
  src/main/java/qp/official/qp/service/QuestionReportService/QuestionReportQueryService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandServiceImpl.java
  src/main/java/qp/official/qp/service/TokenService/TokenService.java
  src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
  src/main/java/qp/official/qp/service/UserService/UserService.java
  src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
  src/main/java/qp/official/qp/validation/validator/ExistAnswerValidator.java
  src/main/java/qp/official/qp/web/controller/AnswerReportController.java
  src/main/java/qp/official/qp/web/controller/AnswerRestController.java
  src/main/java/qp/official/qp/web/controller/HashtagController.java
  src/main/java/qp/official/qp/web/controller/ImageController.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/controller/QuestionReportController.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
  src/main/java/qp/official/qp/web/dto/AnswerLikeRequestDTO.java
  src/main/java/qp/official/qp/web/dto/AnswerResponseDTO.java
  src/main/java/qp/official/qp/web/dto/ImageResponseDTO.java
  src/main/java/qp/official/qp/web/dto/TokenRequestDTO.java
  src/main/java/qp/official/qp/web/dto/TokenResponseDTO.java
  src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
Labels: refactor

#99 [refactor] swagger에 사용법 명시
  src/main/java/qp/official/qp/config/SwaggerConfig.java
  src/main/java/qp/official/qp/web/controller/AnswerRestController.java
  src/main/java/qp/official/qp/web/controller/HashtagController.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
Labels: refactor

#101 [feat] SwaggerUi에서 header 입력 받기
  build.gradle
  src/main/java/qp/official/qp/config/SwaggerConfig.java
  src/main/java/qp/official/qp/converter/AnswerConverter.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
Labels: feat, chore

#103 [refactor] TokenService 리팩토링
  src/main/java/qp/official/qp/converter/TokenConverter.java
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/service/TokenService/TokenService.java
  src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
  src/main/java/qp/official/qp/web/controller/AnswerController.java
  src/main/java/qp/official/qp/web/controller/AnswerReportController.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
  src/main/java/qp/official/qp/web/dto/TokenDTO/AccessTokenDTO.java
  src/main/java/qp/official/qp/web/dto/TokenDTO/RefreshTokenDTO.java
  src/main/java/qp/official/qp/web/dto/TokenDTO/TokenResponseDTO.java
Labels: bug, feat, refactor

#107 [fix] 회원 가입 중 발생하는 오류 수정
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/repository/UserRepository.java
  src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
  src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
Labels: bug

#109 [refactor] 질문 신고, 답변 신고 Swagger 헤더 값 설정 추가
  src/main/java/qp/official/qp/web/controller/AnswerReportController.java
  src/main/java/qp/official/qp/web/controller/QuestionReportController.java
Labels: refactor

#112 [fix] 해시태그 없을때 500에러 수정
  src/main/java/qp/official/qp/validation/validator/ExistHashTagValidator.java
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
Labels: bug

#114 [fix] 질문 신고, 해시태그, 이미지, 유저 입력 값 비어 있는 경우 500대 에러 발생 오류 수정
  src/main/java/qp/official/qp/web/dto/HashtagRequestDTO.java
  src/main/java/qp/official/qp/web/dto/ImageRequestDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionReportRequestDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserAuthDTO.java
  src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
Labels: bug

#116 Deploy 1.1
  build.gradle
  src/main/java/qp/official/qp/apiPayload/ApiResponse.java
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/apiPayload/exception/handler/ImageHandler.java
  src/main/java/qp/official/qp/config/S3Config.java
  src/main/java/qp/official/qp/config/SecretConfig.java
  src/main/java/qp/official/qp/config/SwaggerConfig.java
  src/main/java/qp/official/qp/converter/AnswerConverter.java
  src/main/java/qp/official/qp/converter/ImageConverter.java
  src/main/java/qp/official/qp/converter/TokenConverter.java
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/domain/Image.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/repository/AnswerLikesRepository.java
  src/main/java/qp/official/qp/repository/AnswerReportRepository.java
  src/main/java/qp/official/qp/repository/AnswerRepository.java
  src/main/java/qp/official/qp/repository/ImageRepository.java
  src/main/java/qp/official/qp/repository/UserRepository.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandService.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerQueryServiceImpl.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagService.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagServiceImpl.java
  src/main/java/qp/official/qp/service/ImageService/ImageCommandService.java
  src/main/java/qp/official/qp/service/ImageService/ImageCommandServiceImpl.java
  src/main/java/qp/official/qp/service/ImageService/ImageQueryServiceImpl.java
  src/main/java/qp/official/qp/service/QuestionReportService/QuestionReportQueryService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandServiceImpl.java
  src/main/java/qp/official/qp/service/TokenService/TokenService.java
  src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
  src/main/java/qp/official/qp/service/UserService/UserService.java
  src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
  src/main/java/qp/official/qp/validation/validator/ExistAnswerValidator.java
  src/main/java/qp/official/qp/validation/validator/ExistHashTagValidator.java
  src/main/java/qp/official/qp/web/controller/AnswerController.java
  src/main/java/qp/official/qp/web/controller/AnswerReportController.java
  src/main/java/qp/official/qp/web/controller/HashtagController.java
  src/main/java/qp/official/qp/web/controller/ImageController.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/controller/QuestionReportController.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
  src/main/java/qp/official/qp/web/dto/AnswerLikeRequestDTO.java
  src/main/java/qp/official/qp/web/dto/AnswerReportRequestDTO.java
  src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
  src/main/java/qp/official/qp/web/dto/AnswerResponseDTO.java
  src/main/java/qp/official/qp/web/dto/HashtagRequestDTO.java
  src/main/java/qp/official/qp/web/dto/ImageRequestDTO.java
  src/main/java/qp/official/qp/web/dto/ImageResponseDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionReportRequestDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
  src/main/java/qp/official/qp/web/dto/TokenDTO/AccessTokenDTO.java
  src/main/java/qp/official/qp/web/dto/TokenDTO/RefreshTokenDTO.java
  src/main/java/qp/official/qp/web/dto/TokenDTO/TokenResponseDTO.java
  src/main/java/qp/official/qp/web/dto/TokenRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserAuthDTO.java
  src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
Labels: feat

#124 [fix] 커스텀 Validator null check
  src/main/java/qp/official/qp/validation/validator/ExistAnswerReportValidator.java
  src/main/java/qp/official/qp/validation/validator/ExistAnswerValidator.java
  src/main/java/qp/official/qp/validation/validator/ExistHashTagValidator.java
  src/main/java/qp/official/qp/validation/validator/ExistQuestionReportValidator.java
  src/main/java/qp/official/qp/validation/validator/ExistQuestionValidator.java
  src/main/java/qp/official/qp/validation/validator/ExistUserValidator.java
  src/main/java/qp/official/qp/web/dto/AnswerReportRequestDTO.java
  src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionReportRequestDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
Labels: bug

#127 [feature] QuestionCommandServiceTest.createQuestion Test 구현
  src/main/java/qp/official/qp/converter/QuestionHashtagConverter.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandServiceImpl.java
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
  src/test/java/qp/official/qp/service/QuestionService/QuestionCommandServiceTest.java
Labels: feat

#128 [refactor] 이미지, 유저, 답변 좋아요 Repository 테스트 코드 작성
  build.gradle
  src/main/java/qp/official/qp/domain/User.java
  src/main/resources/application.yml
  src/test/java/qp/official/qp/repository/AnswerLikesRepositoryTest.java
  src/test/java/qp/official/qp/repository/ImageRepositoryTest.java
  src/test/java/qp/official/qp/repository/UserRepositoryTest.java
Labels: refactor

#130 [refactor] 해시태그 및 유저 정보 수정 리팩토링
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagQueryServiceImpl.java
  src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
  src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
Labels: refactor

#131 [fix] 유저 정보 수정 시 입력 되지 않은 값은 null로 수정되는 오류 해결
  src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
Labels: bug

#118 [refactor] 답변 및 질문 신고 테스트 코드 생성
  build.gradle
  src/main/java/qp/official/qp/domain/User.java
  src/test/java/qp/official/qp/repository/AnswerReportRepositoryTest.java
  src/test/java/qp/official/qp/repository/QuestionReportRepositoryTest.java
Labels: refactor

#135 [refactor] QuestionHashtagConverter. Question, Hashtag 연관관계 편의 메서드 수정
  src/main/java/qp/official/qp/converter/QuestionHashtagConverter.java
  src/main/java/qp/official/qp/domain/Hashtag.java
  src/main/java/qp/official/qp/domain/Question.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandServiceImpl.java
  src/test/java/qp/official/qp/service/QuestionService/QuestionCommandServiceTest.java
Labels: refactor

#142 [feat] 답변 서비스 테스트 코드 작성
  src/main/java/qp/official/qp/domain/Answer.java
  src/main/java/qp/official/qp/domain/Question.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
  src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
  src/test/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImplTest.java
  src/test/java/qp/official/qp/service/AnswerService/AnswerQueryServiceImplTest.java
Labels: feat, refactor, test

#144 [test] ImageService 테스트 코드 작성
  src/main/java/qp/official/qp/config/S3Config.java
  src/main/java/qp/official/qp/service/ImageService/ImageCommandService.java
  src/main/java/qp/official/qp/service/ImageService/ImageCommandServiceImpl.java
  src/test/java/qp/official/qp/service/ImageService/ImageCommandServiceImplTest.java
  src/test/java/qp/official/qp/service/ImageService/ImageQueryServiceImplTest.java
Labels: refactor, test

#146 [test] 해시태그 서비스 테스트 코드 작성
  src/main/java/qp/official/qp/web/dto/HashtagRequestDTO.java
  src/test/java/qp/official/qp/service/HashtagService/HashtagCommandServiceTest.java
  src/test/java/qp/official/qp/service/HashtagService/HashtagQueryServiceTest.java
Labels: test

#149 [test] 질문 서비스 테스트 코드 작성
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
  src/test/java/qp/official/qp/service/QuestionService/QuestionCommandServiceTest.java
  src/test/java/qp/official/qp/service/QuestionService/QuestionQueryServiceTest.java
Labels: test

#148 [test] QuestionController.createQuestion 테스트 코드 작성
  src/main/java/qp/official/qp/QpBackendApplication.java
  src/main/java/qp/official/qp/config/JpaEnversConfiguration.java
  src/main/java/qp/official/qp/config/ObjectMapperConfig.java
  src/main/java/qp/official/qp/domain/Question.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/test/java/qp/official/qp/web/controller/QuestionControllerTest.java
Labels: feat, test

#151 [test] ExistUser 테스트 코드 작성
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/validation/validator/ExistUserValidator.java
  src/main/java/qp/official/qp/web/dto/AnswerReportRequestDTO.java
  src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionReportRequestDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
  src/test/java/qp/official/qp/validation/validator/ExistUserValidatorTest.java
Labels: test

#137 [refactor] 질문, 답변, 해시태그 Repo 테스트 코드 작성
  src/main/java/qp/official/qp/converter/AnswerConverter.java
  src/main/java/qp/official/qp/domain/Hashtag.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandService.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
  src/main/java/qp/official/qp/web/controller/AnswerController.java
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
  src/test/java/qp/official/qp/repository/AnswerRepositoryTest.java
  src/test/java/qp/official/qp/repository/HashTagRepositoryTest.java
  src/test/java/qp/official/qp/repository/QuestionRepositoryTest.java
  src/test/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImplTest.java
Labels: test

#158 [feature] 질문 생성, 수정, 삭제 시 유저 유효성 확인
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
Labels: feat

#166 [refactor] 답변 조회 시 응답에 답변 작성한 사용자 명 추가
  src/main/java/qp/official/qp/converter/AnswerConverter.java
  src/main/java/qp/official/qp/web/dto/AnswerResponseDTO.java
Labels: refactor

#163 [test] 이미지, 유저, 해시태그 Controller 테스트 코드 작성
  src/main/java/qp/official/qp/web/controller/UserController.java
  src/main/java/qp/official/qp/web/dto/HashtagRequestDTO.java
  src/main/java/qp/official/qp/web/dto/ImageRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
  src/test/java/qp/official/qp/web/controller/HashtagControllerTest.java
  src/test/java/qp/official/qp/web/controller/ImageControllerTest.java
  src/test/java/qp/official/qp/web/controller/UserControllerTest.java
Labels: refactor, test

#167 [feat] 회원가입 및 로그인시 새로운 회원인지 확인하는 응답 추가
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/repository/UserRepository.java
  src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
  src/main/java/qp/official/qp/web/controller/UserController.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
  src/test/java/qp/official/qp/repository/AnswerRepositoryTest.java
  src/test/java/qp/official/qp/repository/QuestionRepositoryTest.java
  src/test/java/qp/official/qp/repository/UserRepositoryTest.java
Labels: feat, refactor

#168 [refactor] 모든 일대다 연관관계에서 1이 연관관계 관리하도록 변경
  src/main/java/qp/official/qp/domain/Answer.java
  src/main/java/qp/official/qp/domain/Question.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/domain/mapping/QuestionHashTag.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
  src/test/java/qp/official/qp/repository/AnswerRepositoryTest.java
  src/test/java/qp/official/qp/repository/QuestionRepositoryTest.java
Labels: refactor

#171 [refactor] Test 유저 생성시 회원가입과 똑같은 반환값으로 만들기
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
  src/main/java/qp/official/qp/web/controller/UserController.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
Labels: refactor

#177 [feat] 특정 질문에 대한 알림 기능 구현
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/apiPayload/exception/handler/QuestionHandler.java
  src/main/java/qp/official/qp/converter/AnswerConverter.java
  src/main/java/qp/official/qp/converter/QuestionConverter.java
  src/main/java/qp/official/qp/domain/mapping/UserQuestionAlarm.java
  src/main/java/qp/official/qp/repository/UserQuestionAlarmRepository.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerQueryService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandServiceImpl.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
  src/main/java/qp/official/qp/web/controller/AnswerController.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/dto/UserQuestionAlarmResponseDTO.java
Labels: feat, refactor

#186 [feat] 특정 질문 조회시 전문가 답변 갯수, 답변 갯수 같이 반환하도록 수정
  src/main/java/qp/official/qp/converter/QuestionConverter.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/dto/QuestionResponseDTO.java
Labels: feat

#188 [feat] 내가 한 질문 및 알림 설정한 질문 정보 조회 API 구현
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/converter/QuestionConverter.java
  src/main/java/qp/official/qp/repository/QuestionRepository.java
  src/main/java/qp/official/qp/repository/UserQuestionAlarmRepository.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
  src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/dto/QuestionResponseDTO.java
Labels: feat

#191 [feat] 특정 질문의 주변 (이전, 다음) 질문 절보 조회 API 구현
  src/main/java/qp/official/qp/converter/QuestionConverter.java
  src/main/java/qp/official/qp/domain/Question.java
  src/main/java/qp/official/qp/repository/QuestionRepository.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/dto/QuestionResponseDTO.java
Labels: feat

#184 [test] 테스트 질문 데이터 생성
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandServiceImpl.java
  src/test/java/qp/official/qp/QpBackendApplicationTests.java
Labels: test

#195 [feat] User의 Role 변경 API 구현
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/service/UserService/UserService.java
  src/main/java/qp/official/qp/service/UserService/UserServiceImpl.java
  src/main/java/qp/official/qp/web/controller/UserController.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
Labels: feat

#198 [feat] 알림 설정해도 질문 삭제 가능하게 수정
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/domain/Question.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandServiceImpl.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/test/java/qp/official/qp/service/QuestionService/QuestionCommandServiceTest.java
Labels: feat, refactor
