Repository qp-official-org/QP_BACKEND, pull requests merged in 2024-01, with the labels that each got.

#2 test commit
  build.gradle
Labels: chore

#4 chore: 개발 환경 세팅
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: chore

#10 [refactor] Question @Builder.Default 추가
  src/main/java/qp/official/qp/domain/Question.java
Labels: refactor

#14 [chore] 민감정보 숨기기
  src/main/java/qp/official/qp/config/SecretSetting.java
  src/main/resources/application.yml
Labels: chore

#20 [chore] CICD Testing workflow 작성
  .github/workflows/deploy.yml
  .github/workflows/testing.yml
Labels: chore

#18 [chore] dockerfile 작성
  .gitignore
  Dockerfile
Labels: chore

#24 Deploy 0.1
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
Labels: bug

#26 [feat] 질문 기능 API 시그니처 작성
  src/main/java/qp/official/qp/converter/QuestionConverter.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/controller/QuestionRestController.java
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionResponseDTO.java
Labels: feat

#28 [feat] User api 시그니처 생성
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/domain/enums/Role.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
  src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
Labels: feat

#33 [feat] 이미지 등록, 삭제 시그니쳐 구현
  src/main/java/qp/official/qp/web/controller/ImageController.java
  src/main/java/qp/official/qp/web/dto/ImageResponseDTO.java
Labels: feat

#37 [feat] 회원 정보 조회 및 수정 기능
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/domain/enums/UserStatus.java
  src/main/java/qp/official/qp/repository/UserRepository.java
  src/main/java/qp/official/qp/service/UserService.java
  src/main/java/qp/official/qp/service/UserServiceImpl.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
  src/main/java/qp/official/qp/web/dto/UserRequestDTO.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
Labels: feat

#34 [feat] 해시태그 관련 기능 구현
  src/main/java/qp/official/qp/apiPayload/ApiResponse.java
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/apiPayload/exception/handler/HashtagHandler.java
  src/main/java/qp/official/qp/repository/HashtagRepository.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagCommandService.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagCommandServiceImpl.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagQueryService.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagQueryServiceImpl.java
  src/main/java/qp/official/qp/web/controller/HashtagController.java
  src/main/java/qp/official/qp/web/controller/ImageController.java
Labels: feat

#39 [feat]
  src/main/java/qp/official/qp/QpBackendApplication.java
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/converter/HashtagConverter.java
  src/main/java/qp/official/qp/converter/QuestionConverter.java
  src/main/java/qp/official/qp/domain/Answer.java
  src/main/java/qp/official/qp/domain/Hashtag.java
  src/main/java/qp/official/qp/domain/Question.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/domain/mapping/AnswerLikes.java
  src/main/java/qp/official/qp/domain/mapping/AnswerReport.java
  src/main/java/qp/official/qp/domain/mapping/QuestionHashTag.java
  src/main/java/qp/official/qp/domain/mapping/QuestionReport.java
  src/main/java/qp/official/qp/domain/mapping/UserQuestionAlarm.java
  src/main/java/qp/official/qp/repository/QuestionHashTagRepository.java
  src/main/java/qp/official/qp/repository/QuestionRepository.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagService.java
  src/main/java/qp/official/qp/service/HashtagService/HashtagServiceImpl.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionCommandServiceImpl.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
  src/main/java/qp/official/qp/validation/annotation/ExistHashTag.java
  src/main/java/qp/official/qp/validation/annotation/ExistQuestion.java
  src/main/java/qp/official/qp/validation/annotation/ExistUser.java
  src/main/java/qp/official/qp/validation/validator/ExistHashTagValidator.java
  src/main/java/qp/official/qp/validation/validator/ExistQuestionValidator.java
  src/main/java/qp/official/qp/validation/validator/ExistUserValidator.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/dto/HashtagResponseDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionRequestDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionResponseDTO.java
  src/main/resources/application.yml
Labels: feat, refactor, chore

#44 [feat] 테스트 유저 생성 기능 구현
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/service/UserService.java
  src/main/java/qp/official/qp/service/UserServiceImpl.java
  src/main/java/qp/official/qp/web/controller/UserRestController.java
Labels: feat

#45 [feat] 이미지 업로드, 삭제 기능 구현
  build.gradle
  src/main/java/qp/official/qp/QpBackendApplication.java
  src/main/java/qp/official/qp/config/S3Config.java
  src/main/java/qp/official/qp/converter/ImageConverter.java
  src/main/java/qp/official/qp/domain/Image.java
  src/main/java/qp/official/qp/repository/ImageRepository.java
  src/main/java/qp/official/qp/service/ImageService/ImageCommandService.java
  src/main/java/qp/official/qp/service/ImageService/ImageCommandServiceImpl.java
  src/main/java/qp/official/qp/service/ImageService/ImageQueryService.java
  src/main/java/qp/official/qp/service/ImageService/ImageQueryServiceImpl.java
  src/main/java/qp/official/qp/web/controller/ImageController.java
  src/main/java/qp/official/qp/web/dto/ImageRequestDTO.java
  src/main/resources/application.yml
Labels: feat, refactor

#48 [feat] 전체 질문 페이징 조회
  src/main/java/qp/official/qp/converter/HashtagConverter.java
  src/main/java/qp/official/qp/converter/QuestionConverter.java
  src/main/java/qp/official/qp/converter/QuestionHashtagConverter.java
  src/main/java/qp/official/qp/converter/UserConverter.java
  src/main/java/qp/official/qp/domain/Question.java
  src/main/java/qp/official/qp/repository/AnswerRepository.java
  src/main/java/qp/official/qp/repository/QuestionRepository.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
  src/main/java/qp/official/qp/web/dto/HashtagResponseDTO.java
  src/main/java/qp/official/qp/web/dto/QuestionResponseDTO.java
  src/main/java/qp/official/qp/web/dto/UserResponseDTO.java
Labels: feat, refactor, chore

#54 [feat] Question 페이징 조회에 검색 기능 추가
  src/main/java/qp/official/qp/domain/Question.java
  src/main/java/qp/official/qp/repository/QuestionRepository.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryService.java
  src/main/java/qp/official/qp/service/QuestionService/QuestionQueryServiceImpl.java
  src/main/java/qp/official/qp/web/controller/QuestionController.java
Labels: bug, feat

#55 [feat] 답변 등록 및 조회 기능 구현
  src/main/java/qp/official/qp/converter/AnswerConverter.java
  src/main/java/qp/official/qp/converter/QuestionConverter.java
  src/main/java/qp/official/qp/domain/Answer.java
  src/main/java/qp/official/qp/repository/AnswerRepository.java
  src/main/java/qp/official/qp/service/AnswerCommandService.java
  src/main/java/qp/official/qp/service/AnswerCommandServiceImpl.java
  src/main/java/qp/official/qp/service/AnswerQueryService.java
  src/main/java/qp/official/qp/service/AnswerQueryServiceImpl.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandService.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerQueryService.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerQueryServiceImpl.java
  src/main/java/qp/official/qp/validation/annotation/ExistAnswer.java
  src/main/java/qp/official/qp/validation/validator/ExistAnswerValidator.java
  src/main/java/qp/official/qp/web/controller/AnswerRestController.java
  src/main/java/qp/official/qp/web/dto/AnswerRequestDTO.java
  src/main/java/qp/official/qp/web/dto/AnswerResponseDTO.java
Labels: feat, refactor

#65 [fix] Docker 컨테이너 안 TimeZone설정
  Dockerfile
  src/main/java/qp/official/qp/QpBackendApplication.java
Labels: bug

#69 [fix] 특정 질문의 부모 답변 페이징 조회 시 응답에 null 포함되는 오류 수정
  src/main/java/qp/official/qp/converter/AnswerConverter.java
  src/main/java/qp/official/qp/repository/AnswerRepository.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerQueryServiceImpl.java
Labels: bug, refactor

#72 [feat] AWS S3 버킷 초기화 API 작성
  src/main/java/qp/official/qp/repository/ImageRepository.java
  src/main/java/qp/official/qp/service/ImageService/ImageCommandService.java
  src/main/java/qp/official/qp/service/ImageService/ImageCommandServiceImpl.java
  src/main/java/qp/official/qp/web/controller/ImageController.java
Labels: feat

#60 [feat] JWT 및 refreshToken 생성
  build.gradle
  src/main/java/qp/official/qp/config/SecretConfig.java
  src/main/java/qp/official/qp/domain/User.java
  src/main/java/qp/official/qp/repository/UserRepository.java
  src/main/java/qp/official/qp/service/JWTService.java
  src/main/java/qp/official/qp/service/UserService.java
  src/main/java/qp/official/qp/service/UserServiceImpl.java
  src/main/java/qp/official/qp/web/controller/TokenController.java
  src/main/java/qp/official/qp/web/dto/TokenRequest.java
  src/main/java/qp/official/qp/web/dto/UserAuthDTO.java
  src/main/resources/application.yml
Labels: feat

#64 [feat] 답변 좋아요 기능 구현
  src/main/java/qp/official/qp/converter/AnswerConverter.java
  src/main/java/qp/official/qp/converter/AnswerLikesConverter.java
  src/main/java/qp/official/qp/domain/Answer.java
  src/main/java/qp/official/qp/domain/enums/AnswerLikeStatus.java
  src/main/java/qp/official/qp/repository/AnswerLikesRepository.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandService.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerCommandServiceImpl.java
  src/main/java/qp/official/qp/service/AnswerService/AnswerQueryServiceImpl.java
  src/main/java/qp/official/qp/web/controller/AnswerRestController.java
  src/main/java/qp/official/qp/web/dto/AnswerLikeRequestDTO.java
  src/main/java/qp/official/qp/web/dto/AnswerLikeResponseDTO.java
  src/main/java/qp/official/qp/web/dto/AnswerResponseDTO.java
Labels: feat, refactor

#76 [Chore] CI/CD시 환경변수 설정 변경
  .github/workflows/deploy.yml
  EnvBash.sh
  build.gradle
  src/main/java/qp/official/qp/config/SecretConfig.java
Labels: refactor, chore

#82 [refactor] jwt 만료 시간 변경 및 isValidToken refactoring
  src/main/java/qp/official/qp/apiPayload/code/status/ErrorStatus.java
  src/main/java/qp/official/qp/apiPayload/exception/handler/TokenHandler.java
  src/main/java/qp/official/qp/config/SecretConfig.java
  src/main/java/qp/official/qp/repository/UserRepository.java
  src/main/java/qp/official/qp/service/JWTService.java
  src/main/java/qp/official/qp/service/TokenService/TokenService.java
  src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
  src/main/java/qp/official/qp/service/UserService.java
  src/main/java/qp/official/qp/service/UserServiceImpl.java
  src/main/java/qp/official/qp/web/controller/TokenController.java
Labels: refactor

#85 [refactor] isValidToken 문제 수정
  src/main/java/qp/official/qp/service/TokenService/TokenService.java
  src/main/java/qp/official/qp/service/TokenService/TokenServiceImpl.java
  src/main/java/qp/official/qp/web/controller/TokenController.java
Labels: feat, refactor
